# FIXME:
# scons: warning: Two different environments were specified for target Utils.o, PParams.o, Gallery.o
# but they appear to have the same action: $CXX -o $TARGET -c $CXXFLAGS $CCFLAGS $_CCCOMCOM $SOURCES

# Dyna
env = Environment()

env['APP_TARGET'] = 'DynaApp'
env['APP_SOURCES'] = ['DynaApp.cpp', 'Particles.cpp', 'DynaStroke.cpp', 'Utils.cpp',
		'TimerDisplay.cpp', 'HandCursor.cpp', 'PParams.cpp', 'Gallery.cpp']
env['ASSETS'] = ['brushes/*', 'pose-anim/*', 'gfx/game/*', 'gfx/pose/*', 'gfx/watermark.png',
		'gfx/logo.png']
env['RESOURCES'] = ['shaders/*', 'audio/*', 'gfx/cursors/*']
env['ICON'] = '../resources/dynani.icns'
env['DEBUG'] = 0

env = SConscript('../blocks/msaFluid/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/Cinder-NI/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')

# Gallery
env2 = Environment()

env2['APP_TARGET'] = 'DynaGalleryApp'
env2['APP_SOURCES'] = ['DynaGalleryApp.cpp', 'Utils.cpp',
		'PParams.cpp', 'Gallery.cpp']
env2['RESOURCES'] = ['shaders/*', 'audio/*', 'gfx/*']
env2['ASSETS'] = ['gfx/dynagallery/*']
env2['ICON'] = '../resources/dynani.icns'
env2['DEBUG'] = env['DEBUG']

SConscript('../../../scons/SConscript', exports = {'env': env2})

